[build-system]
# wheel to get more lightweight (not EASY-INSTALL) entry-points
requires = ["packaging", "setuptools>=40.8.0", "wheel"]

[tool.isort]
force_grid_wrap = 2
include_trailing_comma = true
multi_line_output = 3
